name: Continuous integration

on: [push] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release
    - name: Publish
      run: dotnet publish ./src/SmartOrderRouter.AdminApi/SmartOrderRouter.AdminApi.csproj --output ../../publish --configuration Release /p:AssemblyVersion=1.0.0
    - name: Check dir
      run: ls ./publish
    - name: Publish to Registry
      uses: SC-Poc/Publish-Docker-Github-Action@master
      with:
        name: swisschains/liquidity-admin-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./publish
        # snapshot: true # use snapshot to push an additional image, which is tagged with {YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}
        tag_names: true
